= Jak přišly květiny na svět?

[quote, H. Heine]
____
Vůně je citem květin.
____

Květiny jsou pro člověka velmi důležité. Provázejí ho celý život. Žádná oslava i loučení se bez nich neobejdou. Jsou pro nás zdrojem krásy, relaxace, inspirace, věštění, magie, potravy, zdobení vlasů a oblečení. Mají nezastupitelné místo na obrazech, v písních, výšivkách, zdobení příbytku, vyprávění, lidské komunikaci. Jsou atributem bohů, různých mýtických bytostí (víly, dryády) a svatých. Vždy byly a jsou nevysychajícím zdrojem symbolů ve všech oblastech lidské činnosti.

Existují různá vyprávění po celém světě o tom, jak se květiny objevily na Zemi. Jednou z nich je pohádka australských černochů.

_Na ostrovech v Jižních mořích žil kdysi dávno kouzelník Byame. Byl přísný, ale spravedlivý a laskavý. Milovali ho lidi, zvěř, ptáci, ryby, květiny - protože je měl rád a chránil je. Když zestárnul, rozloučil se s čaroději, kteří mu sloužili, a odešel do nejvzdálenějšího koutu Země, kde stála nejvyšší hora Ubi-ubi. Vystoupil na ni, aby tam prožil své stáří. Všichni zesmutněli, že je opustil. Nejvíce květiny. A neminul rok, všechny květiny umřely. Pak zemřely i včely a malé černošské děti plakaly, že nemají nic sladkého._

_Existovaly jen tři včelí roje, které žily ve třech starých kvetoucích stromech, protože Byame do nich vryl svoje znamení. Ale nikdo se neopovážil vzít včelám med kvůli těm posvátným znamením. Léta ubíhala._

_Jednou se čarodějové rozhodli, že musí lidem a dětem pomoci. Vydali se k hoře Ubi-ubi, vylezli na její vrchol a tam se setkali se služebním duchem. Vše mu řekli._

_Ten jim slíbil, že o tom Byameovi poví. Druhý den na příkaz Byame služební duch zavedl čaroděje na zvláštní místo, kde rostlo plno různých květů. Každý čaroděj měl natrhat plnou náruč. Pak se měl každý vrátit do svého kraje a počkat na východní vítr a rozhodit v něm květiny. Tak se stalo a všude se květy uchytily a rostly. Pak přiletěly včely a bylo plno medu. A když bylo sucho, říkali lidé: "Teď je ošklivé sucho, ale přijde východní vítr a přinese déšť. Květiny zase rozkvetou. Tak to bude navěky, od těch dob, kdy nám čarodějové přinesli květiny z nebe."_ (zdroj E. Bass)

Proč jsou květiny tak hezké? _Když se Bůh rozhněval na lidstvo a poslal na něho potopu, zachránil se jen Noe se svou rodinou. Bůh mu totiž přikázal, aby vystavil koráb, kam by se vešla jeho rodina, po páru ze všeho živého, semena rostlin, trávy, stromů. Když opadla voda, zeptal se ho Bůh, kde má kvítí. Noe však na ně zapomněl. A tak Bůh přinesl z rajské zahrady jejich semena, a proto jsou kytičky tak hezké._ (zdroj M. Korandová)

Podobná legenda říká, že _Noe na svůj koráb nevzal semena travin, bylin ani stromů, protože Bůh mu to nepřikázal. Pak Bůh seslal potopu a vše bylo na Zemi zničeno. Hospodin zatopil veškerou zem, ale zahradu Eden ponechal nedotčenou._

_Když vody opadaly a Noe poprvé vystoupil z korábu, hořce zaplakal, protože Země byla pustá. A ptal se Hospodina, proč jeho s rodinou, zvířectvo a ptactvo zachránil, když není tráva, obilí, ovoce. Hospodin mu pravil, aby si Noe se svou rodinou lehli tváří na zem. Pak se zvedl velký vítr od východní strany. Vanul od zahrady Eden a přinesl v prachu semena rostlin. Ty se všechny zazelenaly, dřív než Noe zvedl hlavu ze země. Teprve pak vyvedl živočichy z korábu. Jako první letěly včely._

_Byliny a stromy, které byly před potopou, zahynuly a změnily se v kámen, ale ty, které vyrostly po potopě, pocházejí z Ráje, a proto jsou tak krásné._ (zdroj F. Kubka)

Česká pohádka o tom, jak přišly květiny na svět, vypráví: _Na počátku věků vládla nad celou Zemí neproniknutelná tma. Sluneční král sídlil daleko za obzorem a ze svého paláce nikdy nevycházel. Vysoko na obloze svítily hvězdy. Nebyla to však obloha, ani hvězdy. Byla to nekonečná modrá louka, která se klenula nad Zemí. Na té louce rozkvétaly záhony čarovných květů. V těch květech sedávaly překrásné nebeské víly a něžně zpívaly. Zvěst o jejich kráse se donesla až ke Slunci. A ten se rozhodl, že si z těch víl vybere tu nejkrásnější a vezme si ji za manželku._

_Sluneční král vykročil na nebeskou louku. Jeho zlaté vlasy se zažehly oslnivou září a ze Země uprchla tma. Nebeské víly se polekaly toho neznámého jasu a na svých čarovných květech se rychle snášely na Zemi na zelenou louku. A Sluneční král na nebeské louce nenašel žádnou vílu. Zklamaný se vrátil do svého paláce a na svět znovu padla tma. Tehdy se víly tichounce vznesly na oblohu, ale semínka jejich květů už navždy zapustila kořínky do úrodné země. Tak přišly květiny na svět._ (zdroj V. Šťovíček)

Jiná pohádka vypráví toto: _Na začátku byla Země holá a šedá a na ní se tyčila skála, na které stál hrad. V něm žili tři princové a každý z nich měl svého orla, na kterém létal. Jednou uviděli na pusté pláni tančit tři víly. Tam, kde se víly dotkly země, začala rašit zelená tráva. Když dotančily, odlétly na svůj bílý hrad. Princům najednou připadal jejich hrad pustý._

_Vyslali nejstaršího prince s nákladem zlata a šperků. Přiletěl k bílému zámku a tam požádal víly, aby si jeho a bratry vzaly za muže. Byl odmítnut s tím, že je zlato ani šperky nelákají. Druhý den letěl prostřední bratr s drahým kamením a perlami. I on byl odmítnut. Třetí den měl letět nejmladší, ale princové nevěděli, jaký dar mají poslat._

_Najednou uviděli pod hradem starého muže, který měl před sebou stojan, paletu s barvami a štětec. Nejmladší princ ho poprosil, aby ho naučil malovat, že chce namalovat krásný obraz jako dar pro víly._

_Začal malovat barevné květy. Víly je uviděly, přišly blíže a ta nejmladší se ho zeptala, co to maluje. „Květiny. Ta žlutá je pampeliška, malé sluníčko jen pro tebe. Ta modrá je pomněnka, abys na mne nezapomněla. Bílý je lomikán, abys věděla, že láska i kámen rozdrobí. Červená je slzička, protože si vypláčeme oči, když vás nebudeme mít nablízku," řekl nejmladší z bratrů. A víly přistoupily k plátnu, vybíraly z něho květiny a roznášely je po louce. Bratři pak natrhali kytičky, dali je vílám do vlasů a ty řekly, že je to překrásný dar. A princové věděli, že tentokrát je neodmítnou._

_První květiny byly od té chvíle na světě._ (zdroj P. Kettner)

Velmi důležitou úlohu mělo Slunce. Slunce dávalo rostlinám život, a proto se mu přisuzovaly i jiné stvořitelské schopnosti. Jedna pověst vypráví: _Kdysi dávno byla Země pustá a holá. Nic na ni nerostlo. Země byla velice smutná. Občas na ní odpočíval bílý nebeský pták. Byl tak obrovský a měl tak silná křídla, že mohl létat mezi hvězdami. Na některých z nich rostly stromy, na jiných květiny, jinde zase tráva a obilí. Pták chtěl Zemi pomoci a tak přinášel různá semena, ta se ujala a na Zemi se objevily rostliny. Všechny ale byly bílé._

_Jednou se po dešti na obloze objevila duha. Byla tak krásná, že si květiny o duze povídaly až do večera, a dokonce i přes noc. Domluvily se, že poprosí Sluníčko o barvy. Ráno přednesly sluníčku svou prosbu. Následující den na ně čekaly v nádobách různé barvy a každá květina si mohla vybrat. Některé květiny byly s výběrem rychle hotové, jiné chtěli vypadat jako duha a nabíraly si různé barvy. Jiné se neuměly rozhodnout a tak dlouho se rozmýšlely, až žádná barva nezbyla a ony zůstaly bílé._

_A když jednou opět přiletěl bílý nebeský pták, byl tak překvapený tou krásou, že také zatoužil mít duhová křídla. A protože květiny věděly, komu vděčí, že mohou růst na Zemi, každá mu dala trochu ze své barvy. Najednou už to nebyl bílý nebeský pták, ale duhový nebeský pták. A byla to taková krása, že se to nedá vypovědět. A duhový nebeský pták květinám poděkoval tak, že každé daroval vůni._

_A proto jsou květiny nebesky krásné a nebesky voní._

Jiný náhled na to, jak získaly květiny barvu, předkládá toto pohádkové vyprávění: _Původní barvy rostlin byly jednobarevné -- zelené. Později začala Matka příroda uvažovat i o jiných barvách. Na tento nápad přišla, když pohlédla na duhu. Matka příroda dala na vědomí květinám, že bude zdarma rozdávat barvy pro květy a plody. Bude se tak dít několikrát, a to vždy v osvitu jednoho Slunce. Poprvé to bylo v době, kdy odcházela zima a ještě bylo na Zemi trochu sněhu. Začala s barvou bílou. Proto první jarní květiny jsou bílé. Při druhém osvitu Matka příroda se inspirovala barvou Slunce -- žlutou. Tak pokračovala, dokud nebyly všechny barvy rozebrány._ (zdroj B. Šula)

**Rostliny** jsou symbolem obnovy života. Důvodem je jejich neustálá proměna v období růstu, květu, zralosti, vydání plodů a smrti. Rostlinná symbolika vypovídá o významových spojeních jednotlivých rostlin s duchovními obsahy. V mytologii a pohádkách nacházíme příklady úplných nebo částečných proměn rostlin v lidi a naopak, propojení života člověka se životem květiny či stromu.

Rostliny jsou v mnoha kulturách symboly Matky Země a cyklu života. Mnoho z nich je symbolem božstev plodnosti, šťáva rostlin životodárnou tekutinou a některé plody přináší nesmrtelnost. Původ rostlin je různý -- některé se měly zrodit z krve hrdinů či bohů a odkazují tak na smrt a znovuzrození, jiné se zrodily z lidské touhy a trápení a poukazují tak na věčnou sílu lásky, věrnosti, přátelství.

Rostliny symbolizují život, množení ale i krátkověkost, rychlou smrt a obnovu.

Rostlinou lze charakterizovat povahu člověka. Květiny jemné a malé jsou znakem, že nositel je jemná a romantická duše. Rostliny okázalé, s výrazným zbarvením a výraznou vůni, či velice vzácné a drahé, nosívaly ženy výstřední a ty, které na sebe chtěly upoutat pozornost mužů. Rostliny trnité jsou nebezpečné a stávají se oblíbeným motivem mužů, jelikož trny značí moc nad svou obětí a jakousi sílu duševní i tu fyzickou.

Cíleným umístěním určitých rostlin (např. na dveře, za oknem, nad lůžko, pod polštář, na stropní trám, do osobního váčku) můžeme vytvořit ochranný štít proti neštěstí, zlým silám, démonům. Obecně rostliny se špičatými listy se považovaly za nepříznivé, protože tvarem svých listů údajně vytváří negativní energie. Proto se nedoporučovalo je mít v ložnici, v obytných prostorech. Silně vonící květiny se také nedoporučovaly v ložnicích, protože panovala představa, že mohou spícího svou vůní ve snu obloudit, ten pak může ve snu zabloudit a nevrátit se mezi živé.

Podle starobylých teorií se rostliny, které se podobají svou částí určité části těla, tuto část těla léčí.

Rostlinám byly přisuzovány i zázračné schopnosti. Věřilo se v bylinu nesmrtelnosti, která přináší věčné mládí, zdraví a dlouhověkost. Otevírací bylina byla touhou všech zlodějů, protože otevírala každý zámek a cestu k pokladům. Zlaté kapradí přinášelo štěstí a bohatství.

**Flora**, římská bohyně jara a rostlin, byla zobrazována s rohem hojnosti, z kterého se sypaly květy. V současné době bývá vypodobňována jako mladá dívka s bohatou květinovou výzdobou ve vlasech a s náručí plnou rozmanitých květů. V Římě se na její počest slavily Floralie od 28. dubna do 3. května. Při nich hrály velkou roli hetéry. Uvolnění mravů mělo pozitivně ovlivnit veškerý růst v přírodě (agrární rituál, který se později změnil v lidový svátek).

Podle Ovídia _byla Flóra dříve nymfou Chlóridou (zelenkavou), kterou unesl bůh západního větru Zefyros a učinil ji svou chotí. Jako svatební dar jí daroval věčné jaro, čímž se stala bohyní mladé přírody. Chlórida prý darovala Junoně (řec. Héra) zázračný květ, po kterém se bohyně Junona i bez Jupiterova (řec. Zeus) přičinění stala matkou a porodila boha Marta._

**Roh hojnosti** je také symbolem bohyně štěstí Fortuny jako zdroj nevyčerpatelných darů, kterých se dostává člověku bez jeho přímého přičinění. Roh, z něhož se neustále sype ovoce a další osvěžující dary, patřil božské koze Amalthei, jež svým mlékem kojila Dia (1. p. Zeus), když se skrýval před svým otcem Kronem. Po Amaltheině smrti získala jeden z rohů bohyně štěstí a blahobytu Tyché.

Jiná legenda říká, že _když Héraklés (lat. Hercules) bojoval s Achelóem, říčním bohem v podobě býka, ulomil mu roh. Tento roh pak mořské bohyně naplnily plody a stal se rohem hojnosti._

Ve středověkém malířství roh hojnosti s ovocem v blízkosti páru symbolizoval plodnost a to, že vyobrazený pár počne potomka.

V keltské mytologii roh hojnosti obsahuje dary mateřské bohyně. Byl symbolem obnovy a oživení životních sil, proto se z něj pilo. Pití z rohu během hostin mělo svůj rituál.

Slovanskou bohyní jara je v obecném povědomí Vesna (není to původní bohyně, původně tak byla pojmenována personifikace jara) - věčně mladá a krásná, veselá, rozpustilá, proměnlivá a nestála. Má dlouhé zlaté vlasy, které zdobí věnec z jarních květů a zelené šaty. Přilétá na křídlech jarních ptáků (zejména kukačky) a přináší první jarní déšť.

Jaro prý začíná první jarní bouřkou. To když se bůh Perun (bůh severu, bouře, úrody, válek) zadívá do Vesniných očí, obejme ji a přitom mu z ruky vypadne jeho kopí -- blesk.

Pohádka král Slunce a jeho čtyři dcery _vypráví o nejstarším a nejmocnějším králi na světě -- Slunci. Ten má čtyři dcery. Zimu, Jaro, které říká Vesna, Léto a Podzim, které říká Jeseň. Nejraději měl dceru Vesnu. A lidé ji také nejvíce milovali a nadšeně vítali, protože přicházela po kruté Zimě a přinášela naději nového života. Přicházela vždy bosá, v lehoučkých šatech utkaných z mlhy, na zlatých vlasech měla věneček fialek. Každý den splétala nové věnce, tančila po loukách a hájích a zpívala. Vypadalo to, že se jen baví, ale když přicházela převzít vládu její sestra Léto, cítila se velice unavená a těšila se, že bude dlouho spát._ (zdroj H. Bobińska)

Germánskou bohyní jara a plodnosti je Ostara. Krásná lehkonohá dívka obklopená motýly, s náručí plnou květin a s květinami ve vlasech.

**Květiny** patří k symbolům krásy, mládí, jara, dokonalosti, míru, duchovního snažení. Slouží k obřadům a léčení už od pradávna. Jsou symbolem zejména ženské krásy. Také symbolem pomíjivosti a nestálosti. Někdy se květiny uvádějí do souvislosti s dušemi zemřelých.

Jsou symbolem cyklů zrození a smrti, protože kvetou a uvadají. Značí ale i krásu, jemnost, křehkost, avšak najdeme v nich i omamnost či zrádnost, zvláště jedná-li se o květiny pronikavé vůně či rostliny jedovaté. Květiny jsou spojené s magií přírody, s elfy, vílami a postavičkami, které pochází z rostlinné říše. Díky jejich rozmanitosti, co se barev, tvarů, vůni a vlastností týče, jsou takřka nevyčerpatelným námětem nejen pro umění.

Mnohé květiny jsou symbolem určitého státu (Anglie -- růže, Wales -- narcis, Irsko -- jetel, Skotsko -- bodlák, Holandsko -- tulipán).

Pomocí květin lidé vyjadřují své city, myšlenky, estetiku. Darování květiny či kytice vyjadřuje náklonnost, radost ze setkání, vděk, společenské uznání. Květiny byly vždy využívány při náboženských obřadech, rituálech, byly nezbytným doplňkem oslav, svatby a pohřbu. Např. na svatebních dortech jsou často vymodelovány květiny nesoucí určitou symboliku (myrta  láska, břečťan -- manželství, konvalinka -- skromnost a líbeznost, zimolez -- pouta lásky, květ jabloně -- štěstí, levandule -- pevné pouto, oddanost, sedmikráska -- nevinnost, růže -- láska).

Každá kultura má své pohádky, mýty a legendy o květinách a své symboly, které konkrétní květině přiřazují. Jednotlivé květinové symboly vznikají často náhodou a většinou se váží k určité události: dvě anglické růže patnáctého století se v dějinách objevily po drobné hádce; o skotský bodlák se poranili vojáci při dánské invazi; portugalský karafiát si vybrali manifestující občané jako symbol romantické revolty.

Západní svět ovládá růže, ve všech svých podobách. Východní svět si zase podmanil lotosový květ. Lotos je hlavním symbolem Buddhy a stejně tak růže je zase rostlinné znázornění Krista.

**Květ** bývá symbolem úplnosti, dokončení, dokonalého díla a především krásy. Květy jsou posly jara a zdrojem naděje na budoucí plody. Rozvíjející se květ je závislý na slunci a dešti -- symbol odevzdanosti a pokory. Lístky květů bývají sestaveny často radiálně -- symbol Slunce. Záhy uvadají -- symbol nestálosti a pomíjivosti všeho pozemského. Květ je také symbolem lidského života - oba podléhají zákonu zrodu, rozkvětu, zániku. V uctívání zemřelých představují symbol života a jeho pokračování.

Žluté květy souvisí se sluncem, bílé s nevinností, neposkvrněností nebo smutkem a smrtí, červené s láskou, krví a mučednictvím, modré se snem, tajemstvím a věrností.

Květy jako nadčasový estetický prvek se vždy využívaly i ke zdobení osoby, příbytku, sochy.

**Kořen** v symbolice znamená začátek, neviditelný původ existujících věcí, zdroj skryté síly a příslib pokračování života. Větve, listí i květy mohou odumřít a přece rostlina žije dál, pokud zůstává její kořen.

**Semeno** je symbolem života a možnosti i sil, které se ještě nerozvinuly. Je v něm jako v zárodku ukryt celý vývin a život budoucí rostliny. Je nadějí nového života i přežití. Semeno zaseté do země umírá a teprve tak vzniká nový život. Proto je symbolem stálého umírání a rození, zanikání a povstávání i budoucího vzkříšení. Je také znamení sebeoběti ve prospěch druhého ve smyslu hmotném i duchovním.

**Kytice** představuje harmonické spojení rozmanitého v jeden celek. Je nositelem vyjádření určitých emocí (např. kytice pohřební, svatební, promoční, narozeninová). Svůj význam mají i použité druhy květin a jejich barvy (květomluva). Jejich pestrobarevná kombinace je symbolem pestrosti a radosti života. Květiny jako dárek jsou nadčasové a všemi pozitivně přijímány. Darování květiny, kytice, symbolizuje projev náklonnosti, radosti ze setkání, vděku, společenského uznání.

**Ikebana** japonské umění aranžování květin vyjadřuje dokonalou harmonii, která představuje člověka vázaného mezi nebem a zemí. Vychází z budhistické tradice.

Japonci popisují přeměnu květu na ovoce jako stěhování duše rostliny. Na jaře je duše rostliny v květech, v létě v listech, na podzim v ovoci, v zimě ve větvích. Pozornost je věnována váze a všem částem rostliny. Aranžmá se vyhýbá symetrii. Každá životní situace může být vyjádřena uspořádáním květin.

Základní uspořádání tvoří tři linie: nebe (nahoře), lidstvo (uprostřed), země (dole), další skupinou je země, vzduch a voda, třetí skupinou je uspořádání otec, matka dítě. Ikebana je pozemským obrazem nebeské blaženosti.

**Věnec** spojuje dvojí symboliku -- symboliku květin a kruhu. Uzavřená linie kruhu je symbolem času a nekonečnosti (často znázorňován Uroborem - had zakousnutý do svého ocasu). V magických praktikách je kruh využíván jako ochrana proti zlým duchům. Řekové mívali slavnost, při níž svým dvou a tříletým dětem vkládali na hlavu věnec z květů, aby je tak chránili od všeho zla.

Věnec (kruh z květin, listů, větví) bývá proto vnímán jako znamení štěstí, svatosti, plodnosti, zasvěcení. Slouží jako ozdoba i jako symbolický projev úcty a vyznamenání.

Symbolizuje také spojení tohoto i onoho světa (pohřební věnec). Staří Egypťané dávali svým zemřelým „věnce ospravedlnění" -- tím vyjadřovali, že zemřelý bude na onom světě ospravedlněn. Když v antice dávali mrtvému věnec z olivových větviček, přáli mu takto pokoj v hrobě.

Staří Řekové původně věnce vázali jako otevřený kruh. Dionýsos, bůh vína a radovánek, své lidské nevěstě Ariadně daroval takovýto svatební věnec z drahokamů. Byl to symbol nové cesty, nové příležitosti.

V antice věnec sloužil jako ozdoba, vyznamenání a zasvěcení bohu při soutěžích, slavnostech a obětování. Většina božstev byla zdobena věnci ze spletených rostlin, které jim byly přiděleny. Ozdobit někoho věncem původně znamenalo zasvětit jej určitému božstvu. Vavřínové věnce byly symboly boha Apollóna, olivové Dia, piniové Poseidona, věnec z obilných klasů Démétry, fenyklové frýžského boha rolnictví Sabazia.

Věnec z dubového listí se uděloval tomu, kdo zachránil život římského občana. Květinové věnce symbolizovaly také radosti tohoto světa a hýřivého a prostopášného způsobu života. Dle antické lidové pověry má věnec z břečťanu chránit před opilostí (bůh vína Dionýsos býval ověnčen břečťanem). V antice byli věncem věnčeni vítězové her i obětní zvířata. Platil za symbol slávy, cti a radosti.

Původně se uděloval bojovníkům myrtový věnec, a to za vítězství získané nekrvavým způsobem. Vavřínový věnec se uděloval za vítězství získané krvavým způsobem a měl očistit bojovníky od prolité krve. Časem přetrvala myšlenka pocty za vítězství a stalo se zvykem zdobit vítěze vavřínovým věncem. Vládcové a vítězové byli často znázorňováni s vavřínovým věncem. Později byli vavřínovým věncem korunováni i vynikající umělci, básníci a učenci -- „vítězové“ ve svém oboru. Tento zvyk se rozšířil a dochoval dodnes.

V křesťanské symbolice má věnec bohatou symboliku. Představuje vítězství nad temnem a hříchem, např. panenský věnec nebo věneček, jenž nosí děvčata při prvním přijímání, podobně nevěstin věnec. Při církevních slavnostech věnce z chvojí a květů (dnes jsou jimi hojně zdobeny dveře) představovaly symbol věčného života, vzkříšení a radosti.

**Svatojánský věneček**: na sv. Jana Křtitele sbírají dívky devatero kvítí a pletou z něho svatojánský věneček. Má zvláštní moc -- ochraňuje zejména před čarodějnicemi.

**Adventní věnec**: věnce ze zelených rostlin spolu se svíčkami se symbolicky používal už před příchodem křesťanství -- symbolizovaly život jako protiklad studené a tmavé zimy. Dnešní adventní věnec (tvořený z jedlových větviček nebo jiných ozdob) se čtyřmi svícemi jako symbol přípravy na Vánoce a naděje, byl pravděpodobně nejdříve používán v německy mluvících zemích.

Dříve bývalo zvykem ověnčit krále věncem, neboť se věřilo, že jeho královská moc pochází od bohů. Věnec se stal symbolem královské důstojnosti, vítězství a ctnosti. Královské koruny mívaly často podobu kovových, zlatých věnců.

Železná koruna značí zásadovost, ale také tyranství, věnec z růží lásku, trnová koruna je symbolem utrpení. Ježíšovu trnovou korunu v kontextu jeho ukřižování je třeba chápat jako parodii na růžovou korunu římských císařů.

**Zahrada** symbolizuje zkrocenou přírodu, která musí být další péčí kultivovaná. Je to v podstatě uměle založená a ohraničená část přírody. Ráj (Paradisus) se z řečtiny do latiny překládá jako hortus (zahrada), hebrejsky se nazývá Eden (potěšení).

Rajská zahrada odkazuje na Stvořitele, který umístil první lidi do ohrazeného a bezpečného místa. Úrodná, ohrazená a upravená zahrada se považovala za Boží dar. Klášterní zahrady jsou pojaty jako symbol ztraceného ráje.

Mytologická zahrada Hesperidek, ve které rostl strom rodící zlatá jablka, jež byla strážena netvorem, bývá přirovnávána k ráji se stromem života.

V některých kulturách má zahrada podobu mandaly, která v sobě nese hlubokou symboliku jednoty a rovnováhy i celého vesmíru.

V čínské zahradě je ústředním motivem vodní plocha se skalnatými břehy, která představuje moře obklopené horami (pět pahorků symbolizovalo pět světových stran taoistického obrazu světa). Prázdný a zaplněný prostor byl reflexí základních principů jin a jang v harmonickém vztahu, aby do světa lidí vstoupila kosmická rovnováha. Ploché kameny byly považovány za ženské, kuželovité za mužské.

Japonská zahrada usiluje o harmonizaci živlů.

Zahrada představuje symbol pozemského, ale i nebeského ráje, symbol kosmického řádu. Svou ohraničeností jakoby útočištěm před světem je symbolicky blízká oáze a ostrovu.

Zdí obehnaná zahrada, do které lze vstoupit jen úzkou brankou, symbolizuje potíže a překážky, které musí být překonány před dosažením vyššího stupně duševního vývoje. Studna v zahradě obehnané zdí představuje symbol stálosti a pravdivosti i za obtížných okolností. Studna nebo pramen a strom života v zahradě je podobenstvím niterného středu duše.

Z pohledu muže symbolizuje ohrazená zahrada intimní oblast ženského těla.

Ve snové symbolice zahrada znamená místo růstu a péče o niterné projevy života.
