[bibliography]
= Literární zdroje

[bibliography]
- [[[lf2uk]]] Znak 2. lékařské fakulty Univerzity Karlovy v Praze [online] [cit. 2014-05-15] Dostupné z https://www.lf2.cuni.cz/
- [[[lfheid]]] Pečeť lékařské fakulty v Heidelbergu [online] [cit. 2013-09-08] Dostupné z http://www.uni-heidelberg.de/institute/fak5/sonstiges/siegel_eng.html
- [[[lfup]]] Znak Lékařské fakulty Univerzity Palackého v Olomouci; [online] [cit. 2019-03-14] Dostupné z https://www.lf.upol.cz/fileadmin/userdata/LF/Dokumenty/Logomanual/graficky_manual_LF.pdf
- [[[Chromy1984]]] M. Chromý - F. Kučera  Heraldické památky Vyšehradu. Heraldická ročenka 1984, Česká numismatická společnost, pobočka Heraldika, Praha, s.39 - 64, obr. 10, s. 53 [online] [cit. 2019-03-14] Dostupné z http://www.historie.hranet.cz/heraldika/hr/hr1984.pdf

- Becker, U. _Slovník symbolů_. Praha: Portál, 2002, ISBN 80-7178-612-8.
- Cooperová, J. C. _Ilustrovaná encyklopedie tradičních symbolů._ Praha: Mladá Fronta, 1999, ISBN 80-204-0761-8.
- Cornelius, G. _Průvodce noční oblohou._ Praha: Knižní klub a Balila, 1999, ISBN 80-7176-855-3.
- Curtisová, V., S., _Perské mýty._ Praha: Levné knihy KMa, 2006, ISBN 80-7309-415-0.
- Fink, G. _Encyklopedie antické mytologie._ Olomouc: Votobia, 1996, ISBN 80-85885-99-9.
- EDDA bohatýrské písně. Překlad E. Walter. Evropský literární klub, 1942.
- Fontana, D. _The Secret Language of Symbols_. Publisher: Chronicle Books , 1994, ISBN 978-0811804622.
- Francesko, G. Okřídlený býk jako symbol lékařské fakulty. Praha: _Měsíčník Ciba._ 2. roč. č. 16/1935, s. 549 -556.
- Francesko, G. Lékařské prvky v heraldice. Praha: _Měsíčník Ciba._ 3. roč. č.29/1936, s. 995 -- 1003.
- Frith, J. More on the Staff and Serpent of Asclepiu. _ADF Health. Vol 11, N 1 2010 s. 7-8._
- Hart, G. D. Asclepius, God of Medicine. _Can Med Assoc J., Jan 30, 1965; 92(5): 232-236_
- Lévi, E. _Dějiny magie._ Praha: Trigon, 2004, ISBN 80-86159-45-0.
- Lurker, M. _Lexikon bohů a symbolů starých Egypťanů._ Praha: Euromedia Group. K. s. – Knižní klub, 2003, ISBN 0-242-1016-9.
- Martin, R. a kol. _Slovník řecko -- římské mytologie a kultury._ Praha: EWA, 1993, ISBN 80-85764-02-4.
- McCallová, H. _Mezopotamské mýty_. Praha, Levné knihy KMa, 2006, ISBN 80-7309-320-0.
- Nayernouri, T. Asclepius, Saduceus, and Simurgh as Medical Symbols, Part I. _Archives of Iranian Medicine,_ Volume 13, Number 1, January 2010: 61-68.
- Naso, P. Ovidius _Proměny._ Praha, Odeon, 1969.
- Nayernouri, T. Asclepius, Saduceus, and Simurgh as Medical Symbols, Part II Simurgh. _In: Archives of Iranian Medicine,_ Volume 13, Number 3, May 2010: 255-261.
- O´Connell, M., Airey, R. _Znaky a symboly._ Praha: Reader´s Digest Výběr, r. s. o., 2008, ISBN 798-80-86880-96-9.
- Pacher, A. Lékařské symboly a znaky na podobiznách lékařů. Praha: _Měsíčník Ciba._ 2. roč. č. 16/1935, s. 557-562.
- Palivec, V. Aeskulapův atribut (Medikoheraldická studie). _Listy genealogické a heraldické společnosti v Praze. Acta genealogica ac heraldica. č. 11_, únor 1971, s. 9 -- 15.
- Palivec, V. Medikoheraldické symboly. _Listy genealogické a heraldické společnosti v Praze. Acta genealogica ac heraldica. č. 17_, květen 1972, s. 11 -- 13.
- Reed, H. _Symboly a jak jim rozumět._ Praha, Euromedia Group, 2018, ISBN 978-80-7617-033-9
- Royt, J., Šedinová, H. _Slovník symbolů._ Praha: Mladá Fronta, 1998, ISBN 80-204-0740-5.
- Schott, H. _Kronika medicíny._ Praha: Fortuna Print, 1994. ISBN 80-85873-16-8.
- Starý, R. _Cherión, asklépiovská medicína a jungovská psychologie (Eseje)_. Praha: Sagittarius, 2000, ISBN 80-86270-03-3.
- Trencsényi, I. – Waldapfel _Mytologie._ Praha: Odeon, 1967, ISBN 01-0567-67.
- Turner, C., W. Jak se stal had symbolem lékařství. Praha: _Měsíčník Ciba._ 2. roč. č. 16/1935, s. 539 -- 547.
- Wilcox, R., A., Whitham, E. _The Symbol of Modern Medicine: Why Ona Snake Is More Then Two._ Annals of Internal Medicine, 2003; 138 (8): 673-677 [online] [cit. 2014-01-09] Dostupné z http://annals.org/article.aspx?articleid=716360 ; DOI: 10.7326/0003-4819-138-8-200304150-00016
- Willis, R. _Mytologie světa._ Praha: Slovart, 1997, ISBN 80-7209-034-8.
